import { OpenAPI } from "@/api";
import { getStoredToken, handleUnauthorized } from "@/util/authSession";

/**
 * Runtime configuration for the generated API client.
 *
 * `api/core/OpenAPI.ts` is regenerated by the codegen (see commands.md) and any
 * edit to it is overwritten, so base URL and auth token are configured here instead.
 *
 * Set via EXPO_PUBLIC_API_URL: frontend/.env for local dev, frontend/.env.production
 * and the production build env in eas.json for release builds. Expo inlines
 * EXPO_PUBLIC_-prefixed vars into the bundle at build time.
 */
export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || "http://localhost:8000";

/** A rejected login also 401s; that's a bad password, not an expired session. */
const LOGIN_PATH = "/login";

let fetchPatched = false;

/**
 * The generated client issues every request through the global fetch and has no
 * response interceptor, so this is the only place we can see all API responses.
 * Call sites that swallow their errors are covered too.
 */
function installUnauthorizedInterceptor() {
    if (fetchPatched) {
        return;
    }
    fetchPatched = true;

    const originalFetch = globalThis.fetch;

    globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
        const response = await originalFetch(input, init);

        const url =
            typeof input === "string" ? input
            : input instanceof URL ? input.toString()
            : input.url;

        // Only our own API — third-party calls (e.g. the ESPN player search) shouldn't log anyone out.
        const isApiRequest = url.startsWith(API_BASE_URL);
        const isLoginRequest = url.startsWith(`${API_BASE_URL}${LOGIN_PATH}`);

        if (response.status === 401 && isApiRequest && !isLoginRequest) {
            await handleUnauthorized();
        }

        return response;
    };
}

export function configureApi() {
    OpenAPI.BASE = API_BASE_URL;

    // Resolved per request, so it picks up the token stored at login without a restart.
    // The backend (fastapi-login) reads it as `Authorization: Bearer <token>`.
    OpenAPI.TOKEN = async () => (await getStoredToken()) ?? "";

    installUnauthorizedInterceptor();
}
